# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v2
name: waypoint-nodejs
description: Helm chart example for Waypoint
type: application
version: 0.1.0
appVersion: "1.0.0"
